/* Rally2Rumble gallery builder.
   Put photos in:
     photos/photographer/   -> shown as "Photographer"
     photos/guests/         -> shown as "Guests"
   (photos placed directly in photos/ count as guests)
   Then run:  node generate-gallery.js
   This rewrites java/gallery-data.js with every photo it finds. */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, 'photos');
const out = path.join(__dirname, 'java', 'gallery-data.js');
const isImg = /\.(jpe?g|png|webp|gif)$/i;

const groups = [
  { dir: 'photographer', type: 'photographer', by: 'Photographer' },
  { dir: 'guests', type: 'guest', by: 'Guest' },
  { dir: '', type: 'guest', by: 'Guest' }
];

const list = [];
groups.forEach(g => {
  const full = path.join(root, g.dir);
  if (!fs.existsSync(full)) fs.mkdirSync(full, { recursive: true });
  fs.readdirSync(full, { withFileTypes: true })
    .filter(f => f.isFile() && isImg.test(f.name))
    .map(f => f.name)
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
    .forEach(name => list.push({
      file: g.dir ? g.dir + '/' + name : name,
      by: g.by,
      type: g.type,
      caption: ''
    }));
});

const text =
  '/* Generated by generate-gallery.js. Do not edit by hand, run the script again instead. */\n' +
  'window.GALLERY = ' + JSON.stringify(list, null, 2) + ';\n';

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, text);
console.log('Done. ' + list.length + ' photo(s) added to java/gallery-data.js');
